name = "GslibIO"
uuid = "4610876b-9b01-57c8-9ad9-06315f1a66a5"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "1.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Meshes = "0.24, 0.25"
Tables = "1.3"
julia = "1.6"
